name: munaro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # 기본 패키지 및 상태 관리
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1

  # 소셜 로그인 패키지
  google_sign_in: ^6.2.1         
  kakao_flutter_sdk_user: ^1.9.1 

  # 백엔드 통신 패키지
  dio: ^5.4.3       
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/